name: debug-vault-oidc

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show OIDC claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: 'https://github.com/boateng0303'

      - name: Import secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: http://34.234.69.198:8200
          method: jwt
          role: gh-actions-role
          secrets: |
            aws/creds/terraform-role access_key | AWS_ACCESS_KEY_ID ;
            aws/creds/terraform-role secret_key | AWS_SECRET_ACCESS_KEY
