name: Terraform with Vault via GitHub OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug OIDC claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: https://github.com/boateng0303

      - name: Import AWS credentials from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: http://34.234.69.198:8200
          method: jwt
          role: gh-actions-role
          jwtGithubAudience: https://github.com/boateng0303
          secrets: |
            aws/creds/terraform-role access_key | AWS_ACCESS_KEY_ID ;
            aws/creds/terraform-role secret_key | AWS_SECRET_ACCESS_KEY

      - name: Verify AWS caller identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
